### ISSUE TITLE
Not working On Expo

### ISSUE THREAD

**Issue by Barklegne** [webyonet/react-native-mathjax-html-to-svg#1]
Am using expo its throwing the following error 

'Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.'

what shall I do?

**Comment by webyonet** [comment]
Hello there,
I have never done a test with expo. No such error occurs with pure react-native.
I will fix this error in expo as soon as possible

**Comment by webyonet** [comment]
I noticed that I made some mistakes in the documentation.

Firstly, do the setup as below:
```bash
$ expo install react-native-mathjax-html-to-svg 
$ expo install react-native-svg
```
Change the import method as follows:
```javascript
import { MathJaxSvg } from 'react-native-mathjax-html-to-svg';
```

**Comment by Barklegne** [comment]
> I noticed that I made some mistakes in the documentation.
> 
> Firstly, do the setup as below:
> 
> ```shell
> $ expo install react-native-mathjax-html-to-svg 
> $ expo install react-native-svg
> ```
> 
> Change the import method as follows:
> 
> ```js
> import { MathJaxSvg } from 'react-native-mathjax-html-to-svg';
> ```

Thanks brother its working fine now.

**Comment by zaptrem** [comment]
@webyonet I'm still getting this issue with Expo Web SDK 43:

```
Something went wrong:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `GenerateSvgComponent`.
```

Any idea what could be wrong?

Thanks


EDIT: I fixed it and described what happened here: https://github.com/webyonet/react-native-mathjax-html-to-svg/issues/7
