### ISSUE TITLE
Line break after the equation. 

### ISSUE THREAD

**Issue by miriantsirekidze** [webyonet/react-native-mathjax-html-to-svg#18]
Hello, I have math question where i use equation, inline. it looks like this:
find $A\\cup B$, if A={-3; -12; 0; 1; 4; 7} and B={-12; -1; 0; 5; 7}

the issue is that after "find $A\\cup B$" the ", if A={-3; -12; 0; 1; 4; 7} and B={-12; -1; 0; 5; 7}" ends up on the next line. it is fine if the question is something like "find $A\\cup B$, if A={-3; -12; 0; 1; 4; 7}" since the width has enough pixels to not create a new line but if the whole sentence is long enough to not fit in one line then after mathjax formula, the rest of the sentence is on new line.

Looked around and found a stackoverflow answer: 

"The line break issue you are experiencing is likely due to MathJax injecting a div element around each rendered formula. This is the default behavior of MathJax when it processes inline math.". But i don't know how this can be applied to the library.

Here is the code:

<View style={{ marginTop: 50, flex: 1 }}>
     <View style={{ justifyContent: 'center', alignItems: 'center', marginTop: '10%',}}>
         <MathJaxSvg
             fontSize={16}
             color="#000000"          
             style={{marginHorizontal: 20, marginBottom: 20}}
             fontCache={true}
         >
             {equation on the second line}
        </MathJaxSvg>
    </View>
</View>

**Comment by Christian-Klempau** [comment]
How did you solve it?
