### ISSUE TITLE
Miss break line "\n"

### ISSUE THREAD

**Issue by daiquangduy** [webyonet/react-native-mathjax-html-to-svg#2]
Miss break line "\n"

**Comment by webyonet** [comment]
i didn't see a problem

```javascript
<MathJaxSvg fontSize={16} color="#3A4759" fontCache={true}>
   {`first \n second \(6.5\)`}
</MathJaxSvg>
```

![image](https://user-images.githubusercontent.com/973302/125689437-6a44379e-957b-49e1-97ae-29e2f0141273.png)
