### ISSUE TITLE
Text alignment is not good

### ISSUE THREAD

**Issue by hristowwe** [webyonet/react-native-mathjax-html-to-svg#4]
I have tried this package and it looks great but i have problem with rendering text alignment. It cannot be centered. Look image
![image](https://user-images.githubusercontent.com/57602380/131361235-a330dd54-a222-4b76-9a9f-08b89022f8c3.png)
I want to center that text.

**Comment by hristowwe** [comment]
I think i have found solution. go to the index.js file and on the 113 line change textAlign: 'center' look image below
![image](https://user-images.githubusercontent.com/57602380/131361829-4428ec27-0b9e-4ed5-849f-7dfab2ebc1ce.png)

**Comment by webyonet** [comment]
You do not have to do this. 
You can give html inline style for alignment
```html
<span style="text-align:left">...</span>
```
