### ISSUE TITLE
When using html tags text going to new line

### ISSUE THREAD

**Issue by hristowwe** [webyonet/react-native-mathjax-html-to-svg#5]
I have tried to use html tags. First i tried without it like 
```
          <MathJaxSvg
            isCenter={true}
            fontSize={16}
            color={"white"}
            fontCache={false}
          >
            {`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the`}
          </MathJaxSvg>
```
and i got this output
![image](https://user-images.githubusercontent.com/57602380/131475510-5a3ce752-3cb6-4c25-bb08-46ac04269ff0.png)
Then when i add for example <u> tag it breaks where word is 
```
          <MathJaxSvg
            isCenter={true}
            fontSize={16}
            color={"white"}
            fontCache={false}
          >
            {`Lorem Ipsum is simply dummy text of the printing and typesetting <u>industry</u>. Lorem Ipsum has been the industry's standard dummy text ever since the`}
          </MathJaxSvg>
```
![image](https://user-images.githubusercontent.com/57602380/131475641-5698cea0-1626-457e-85ef-34155007f6d2.png)
How to fix that. It creates new line every time i use html tag? 

Also changed file index.js like 
![image](https://user-images.githubusercontent.com/57602380/131475996-59a28de8-7443-4982-9eab-8bdc64190ad5.png)
Add justifyContent

**Comment by hristowwe** [comment]
Any ideas?

**Comment by webyonet** [comment]
yes, it creates a new `<Text>` component with each HTML tag. Because this is how mathjax parses.
I convert the list given by mathjax as `<Text>` or `<Svg>` as native component

**Comment by webyonet** [comment]
If you want to add `justifyContent` you can do as follows:

```javascript
<MathJaxSvg
    fontSize={16}
    color={"white"}
    fontCache={false}
    style={{ justifyContent:'center' }} // this line
>
   {`...`}
</MathJaxSvg>
```

**Comment by hristowwe** [comment]
Is it possible without adding new line each time?

**Comment by webyonet** [comment]
for this, an end-to-end html parser needs to be written. this situation negatively affects performance.
because mathjax is already parsing the html, a second parser will delay the response quite a bit.

**Comment by hristowwe** [comment]
Ye ok thanks

**Comment by hristowwe** [comment]
But why in example text in not going on new line 
![image](https://user-images.githubusercontent.com/57602380/132062282-282b3a3d-4a34-4b43-a040-806c469fc9af.png)
